services:
  hydra-node:
    image: ghcr.io/cardano-scaling/hydra-node:2.2.0
    restart: always
    command:
      [ "--api-host", "0.0.0.0"
      , "--monitoring-port", "6001"
      , "--hydra-signing-key", "/etc/hydra/hydra-user.sk"
      , "--ledger-protocol-parameters", "/etc/hydra/protocol-parameters.json"
      , "--offline-head-seed", "0001"
      , "--initial-utxo", "/etc/hydra/utxo.json"
      ]
    ports:
      - "4001:4001"
    volumes:
      - ./hydra-user.sk:/etc/hydra/hydra-user.sk:ro
      - ./protocol-parameters.json:/etc/hydra/protocol-parameters.json:ro
      - ./utxo.json:/etc/hydra/utxo.json:ro

  hydra-tx3:
    image: ghcr.io/tx3-lang/tx3-hydra:latest
    restart: always
    depends_on:
      - hydra-node
    ports:
      - "8164:8164"
    environment:
      - RUST_LOG=info
    volumes:
      - ./config.toml:/etc/tx3hydra/config.toml
