name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: commit_hash
        run: echo "hash=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Generate manifest tables
        id: manifest_tables
        run: |
          tables=$(scripts/generate-manifest-tables.sh)
          echo "tables<<EOF" >> $GITHUB_OUTPUT
          echo "$tables" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.commit_hash.outputs.hash }}
          name: Release ${{ steps.commit_hash.outputs.hash }}
          body: |
            This release includes the following toolchain manifests:

            ${{ steps.manifest_tables.outputs.tables }}
          files: |
            manifest-stable.json
            manifest-beta.json
            manifest-nightly.json
          draft: false
          prerelease: false
